apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bc0192-dev

resources:
- ../../bases/crunchy-cluster/
- ../../bases/monitoring/

patches:
  - patch: |-
      - op: replace
        path: /spec/instances/0/resources
        value:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
      - op: replace
        path: /spec/patroni/dynamicConfiguration/postgresql/parameters
        value:
          max_connections: 500
          max_slot_wal_keep_size: 128MB
          max_wal_size: 128MB
          min_wal_size: 32MB
          shared_buffers: 250MB
          wal_buffers: "-1"
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: 1Gi
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/volume/volumeClaimSpec/resources/requests/storage
        value: 1Gi
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/schedules/full
        value: 0 8 * * *
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/schedules/incremental
        value: 0 0,4,12,16,20 * * *
    target:
      kind: PostgresCluster
      name: traction-database
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dts-bc0192-dev-agent.apps.silver.devops.gov.bc.ca
    target:
      kind: Ingress
      name: monitoring-grafana-agent
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: bc0192-dev
    target:
      kind: RoleBinding
      name: monitoring-grafana-agent
