apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: bc0192-test-traction-database:postgres-operator.crunchydata.com/PostgresCluster:bc0192-test/traction-database
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"postgres-operator.crunchydata.com/v1beta1","kind":"PostgresCluster","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"bc0192-test-traction-database:postgres-operator.crunchydata.com/PostgresCluster:bc0192-test/traction-database"},"labels":{"devops.gov.bc.ca/gitops-app-shared":"bc0192-test-traction-database"},"name":"traction-database","namespace":"bc0192-test"},"spec":{"backups":{"pgbackrest":{"global":{"repo1-block":"y","repo1-bundle":"y","repo1-retention-archive":"1","repo1-retention-archive-type":"incr","repo1-retention-diff":"6","repo1-retention-full":"1","repo1-retention-full-type":"count"},"repoHost":{"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"150m","memory":"256Mi"}}},"repos":[{"name":"repo1","schedules":{"differential":"0 0 * * 1-6","full":"0 0 * * 0","incremental":"30 * * * *"},"volume":{"volumeClaimSpec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"64Gi"}},"storageClassName":"netapp-file-standard"}}}],"sidecars":{"pgbackrest":{"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"250m","memory":"256Mi"}}}}}},"instances":[{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"postgres-operator.crunchydata.com/cluster":"traction-database","postgres-operator.crunchydata.com/instance-set":"ha"}},"topologyKey":"kubernetes.io/hostname"},"weight":1}]}},"dataVolumeClaimSpec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"16Gi"}},"storageClassName":"netapp-block-standard"},"name":"ha","replicas":2,"resources":{"limits":{"cpu":3,"memory":"4000Mi"},"requests":{"cpu":"200m","memory":"820Mi"}},"sidecars":{"replicaCertCopy":{"resources":{"limits":{"cpu":"100m","memory":"64Mi"},"requests":{"cpu":"1m","memory":"32Mi"}}}}}],"monitoring":{"pgmonitor":{"exporter":{"resources":{"limits":{"cpu":"250m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"64Mi"}}}}},"openshift":true,"patroni":{"dynamicConfiguration":{"postgresql":{"parameters":{"max_connections":500,"max_slot_wal_keep_size":"128MB","max_wal_size":"1GB","min_wal_size":"32MB","shared_buffers":"500MB","wal_buffers":"-1"},"pg_hba":["host all all 0.0.0.0/0 md5","host all all 0.0.0.0/0 trust","host all all ::1/128 trust"]}},"leaderLeaseDurationSeconds":30,"port":8008,"syncPeriodSeconds":10},"port":5432,"postgresVersion":14,"proxy":{"pgBouncer":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"postgres-operator.crunchydata.com/cluster":"traction-database","postgres-operator.crunchydata.com/role":"pgbouncer"}},"topologyKey":"kubernetes.io/hostname"},"weight":1}]}},"config":{"global":{"client_tls_sslmode":"disable"}},"port":5432,"replicas":1,"resources":{"limits":{"cpu":"50m","memory":"128Mi"},"requests":{"cpu":"1m","memory":"64Mi"}}}},"userInterface":{"pgAdmin":{"dataVolumeClaimSpec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}},"users":[{"name":"acapy","options":"CREATEDB CREATEROLE"},{"name":"walletman","options":"CREATEDB CREATEROLE"},{"name":"pgadmin","options":"SUPERUSER"}]}}
    postgres-operator.crunchydata.com/pgbackrest-backup: "2024-04-11T16:33:27Z"
  creationTimestamp: "2023-11-17T15:04:59Z"
  finalizers:
  - postgres-operator.crunchydata.com/finalizer
  generation: 26
  labels:
    devops.gov.bc.ca/gitops-app-shared: bc0192-test-traction-database
  name: traction-database
  namespace: bc0192-test
  resourceVersion: "12278446127"
  uid: b23abc47-0bb6-4cf5-a23e-8181937d0db0
spec:
  backups:
    pgbackrest:
      global:
        repo1-block: "y"
        repo1-bundle: "y"
        repo1-retention-archive: "1"
        repo1-retention-archive-type: incr
        repo1-retention-diff: "6"
        repo1-retention-full: "1"
        repo1-retention-full-type: count
      manual:
        options:
        - --type=differential
        repoName: repo1
      repoHost:
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 150m
            memory: 256Mi
      repos:
      - name: repo1
        schedules:
          differential: 0 0 * * 1-6
          full: 0 0 * * 0
          incremental: 30 * * * *
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 64Gi
            storageClassName: netapp-file-standard
      sidecars:
        pgbackrest:
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
  instances:
  - affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: traction-database
                postgres-operator.crunchydata.com/instance-set: ha
            topologyKey: kubernetes.io/hostname
          weight: 1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 16Gi
      storageClassName: netapp-block-standard
    name: ha
    replicas: 2
    resources:
      limits:
        cpu: 3
        memory: 4000Mi
      requests:
        cpu: 200m
        memory: 820Mi
    sidecars:
      replicaCertCopy:
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 1m
            memory: 32Mi
  monitoring:
    pgmonitor:
      exporter:
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
  openshift: true
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: 500
          max_slot_wal_keep_size: 128MB
          max_wal_size: 1GB
          min_wal_size: 32MB
          shared_buffers: 500MB
          wal_buffers: "-1"
        pg_hba:
        - host all all 0.0.0.0/0 md5
        - host all all 0.0.0.0/0 trust
        - host all all ::1/128 trust
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  port: 5432
  postgresVersion: 14
  proxy:
    pgBouncer:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: traction-database
                  postgres-operator.crunchydata.com/role: pgbouncer
              topologyKey: kubernetes.io/hostname
            weight: 1
      config:
        global:
          client_tls_sslmode: disable
      port: 5432
      replicas: 1
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
        requests:
          cpu: 1m
          memory: 64Mi
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      replicas: 1
  users:
  - name: acapy
    options: CREATEDB CREATEROLE
  - name: walletman
    options: CREATEDB CREATEROLE
  - name: pgadmin
    options: SUPERUSER
status:
  conditions:
  - lastTransitionTime: "2024-11-13T19:57:05Z"
    message: pgBackRest dedicated repository host is ready
    observedGeneration: 26
    reason: RepoHostReady
    status: "True"
    type: PGBackRestRepoHostReady
  - lastTransitionTime: "2024-08-28T17:31:36Z"
    message: Status is missing for the replica creation repo
    observedGeneration: 26
    reason: RepoStatusMissing
    status: Unknown
    type: PGBackRestReplicaRepoReady
  - lastTransitionTime: "2024-08-28T17:31:36Z"
    message: Status is missing for the replica create repo
    observedGeneration: 26
    reason: RepoStatusMissing
    status: Unknown
    type: PGBackRestReplicaCreate
  - lastTransitionTime: "2024-09-23T19:41:25Z"
    message: Deployment has minimum availability.
    observedGeneration: 26
    reason: MinimumReplicasAvailable
    status: "True"
    type: ProxyAvailable
  - lastTransitionTime: "2024-04-11T16:45:32Z"
    message: Manual backup did not complete successfully
    observedGeneration: 21
    reason: ManualBackupFailed
    status: "False"
    type: PGBackRestManualBackupSuccessful
  - lastTransitionTime: "2024-11-21T04:40:30Z"
    message: One or more volumes cannot be resized
    observedGeneration: 26
    reason: Invalid
    status: "False"
    type: PersistentVolumeResizing
  databaseRevision: 559678bf8f
  instances:
  - name: ha
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
  monitoring:
    exporterConfiguration: 6f6c747c8b
  observedGeneration: 26
  patroni:
    systemIdentifier: "7302447472327827536"
  pgbackrest:
    manualBackup:
      failed: 7
      finished: true
      id: "2024-04-11T16:33:27Z"
      startTime: "2024-04-11T16:35:39Z"
    repoHost:
      apiVersion: apps/v1
      kind: StatefulSet
      ready: true
    scheduledBackups:
    - cronJobName: traction-database-repo1-diff
      failed: 7
      repo: repo1
      startTime: "2024-09-09T00:00:02Z"
      type: diff
    - completionTime: "2024-11-19T00:00:29Z"
      cronJobName: traction-database-repo1-diff
      repo: repo1
      startTime: "2024-11-19T00:00:02Z"
      succeeded: 1
      type: diff
    - completionTime: "2024-11-20T00:00:29Z"
      cronJobName: traction-database-repo1-diff
      repo: repo1
      startTime: "2024-11-20T00:00:02Z"
      succeeded: 1
      type: diff
    - completionTime: "2024-11-21T00:00:29Z"
      cronJobName: traction-database-repo1-diff
      repo: repo1
      startTime: "2024-11-21T00:00:02Z"
      succeeded: 1
      type: diff
    - cronJobName: traction-database-repo1-full
      failed: 7
      repo: repo1
      startTime: "2024-09-08T00:00:02Z"
      type: full
    - completionTime: "2024-11-03T00:03:20Z"
      cronJobName: traction-database-repo1-full
      repo: repo1
      startTime: "2024-11-03T00:00:02Z"
      succeeded: 1
      type: full
    - completionTime: "2024-11-10T00:03:31Z"
      cronJobName: traction-database-repo1-full
      repo: repo1
      startTime: "2024-11-10T00:00:02Z"
      succeeded: 1
      type: full
    - completionTime: "2024-11-17T00:03:22Z"
      cronJobName: traction-database-repo1-full
      repo: repo1
      startTime: "2024-11-17T00:00:02Z"
      succeeded: 1
      type: full
    - cronJobName: traction-database-repo1-incr
      failed: 7
      repo: repo1
      startTime: "2024-09-09T01:30:00Z"
      type: incr
    - completionTime: "2024-11-21T02:30:12Z"
      cronJobName: traction-database-repo1-incr
      repo: repo1
      startTime: "2024-11-21T02:30:00Z"
      succeeded: 1
      type: incr
    - completionTime: "2024-11-21T03:30:10Z"
      cronJobName: traction-database-repo1-incr
      repo: repo1
      startTime: "2024-11-21T03:30:00Z"
      succeeded: 1
      type: incr
    - completionTime: "2024-11-21T04:30:26Z"
      cronJobName: traction-database-repo1-incr
      repo: repo1
      startTime: "2024-11-21T04:30:00Z"
      succeeded: 1
      type: incr
  proxy:
    pgBouncer:
      postgresRevision: 7fdb984977
      readyReplicas: 1
      replicas: 1
  userInterface:
    pgAdmin:
      usersRevision: 79bd7c8944
  usersRevision: 94b458d6
