apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ca7f8f-dev

resources:
- ../../bases/monitoring/

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dts-ca7f8f-dev-agent.apps.silver.devops.gov.bc.ca
    target:
      kind: Ingress
      name: monitoring-grafana-agent
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: ca7f8f-dev
    target:
      kind: RoleBinding
      name: monitoring-grafana-agent
