global:
  ingressSuffix: -sandbox.apps.silver.devops.gov.bc.ca

endorser-service:
  api:
    image:
      tag: 1.1.3
    acapyAdminUrl: https://endorser-agent-webvh-admin-sandbox.apps.silver.devops.gov.bc.ca
    publicName: "BC Endorser Service (sandbox)"
    publicDesc: "An endorser service for BC issuer agents"
    adminUser: endorser-admin
    logLevel: info
    autoAcceptConnections: true
    autoAcceptAuthors: true
    autoEndorseRequests: true
    autoEndorseTxnTypes: ""

  acapy:
    image:
      tag: 1.1.3
    agentUrl: "https://endorser-agent-webvh-sandbox.apps.silver.devops.gov.bc.ca"
    adminUrl: "https://endorser-agent-webvh-admin-sandbox.apps.silver.devops.gov.bc.ca"
    plugin-config.yml:
      webvh:
        server_url: "https://sandbox.bcvh.vonx.io"

    extraDeploy:
      - apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: "{{ .Release.Name }}-acapy-postgres"
        spec:
          podSelector:
            matchLabels:
              app.kubernetes.io/name: acapy-postgres
              app.kubernetes.io/instance: "{{ .Release.Name }}"
          ingress:
            - from:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/name: acapy
                      app.kubernetes.io/instance: "{{ .Release.Name }}"
              ports:
                - port: 5432
                  protocol: TCP

  proxy:
    ingress:
      hosts:
        - host: endorser-agent-webvh-sandbox.apps.silver.devops.gov.bc.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: agent
        - host: endorser-agent-webvh-admin-sandbox.apps.silver.devops.gov.bc.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: admin
        - host: endorser-api-webvh-sandbox.apps.silver.devops.gov.bc.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
              servicePort: endorser
