apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bc0192-tools

resources:
- ../../bases/monitoring/

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dts-bc0192-tools-agent.apps.silver.devops.gov.bc.ca
    target:
      kind: Ingress
      name: monitoring-grafana-agent
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: bc0192-tools
    target:
      kind: RoleBinding
      name: monitoring-grafana-agent
