global:
  ingressSuffix: -prod.apps.silver.devops.gov.bc.ca

traction:
  acapy:
    image:
      pullPolicy: Always

    secrets:
      api:
        retainOnUninstall: true
        existingSecret: "traction-acapy-api"

    extraEnvVarsSecret: "traction-acapy-plugin-innkeeper"

    argfile.yml:
      preserve-exchange-records: false
      tails-server-base-url: https://tails.vonx.io
      tails-server-upload-url: https://tails.vonx.io

    ledgers.yml:
      - id: candy-prod
        is_production: true
        is_write: true
        genesis_url: "https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/prod/pool_transactions_genesis"
        endorser_did: "LTNyw5R14J66CrF7tmV3i8"
        endorser_alias: "candy-prod-endorser"

    plugin-config.yml:
      traction_innkeeper:
        innkeeper_wallet:
          print_key: false
          print_token: false
          connect_to_endorser:
            - endorser_alias: candy-prod-endorser
              ledger_id: candy-prod
          create_public_did:
            - candy-prod
        reservation:
          expiry_minutes: 2880
          auto_approve: false
          auto_issuer: false

    walletStorageConfig:
      url: traction-database-primary:5432

    walletStorageCredentials:
      admin_account: walletman
      existingSecret: traction-database-acapy
      secretKeys:
        adminPasswordKey: walletman-password
        userPasswordKey: acapy-password

    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

    networkPolicy:
      enabled: true
      ingress:
        enabled: true
        namespaceSelector:
          network.openshift.io/policy-group: ingress

    ingress:
      agent:
        enabled: true
        hostname: traction-acapy.apps.silver.devops.gov.bc.ca
        annotations:
          route.openshift.io/termination: edge
      admin:
        enabled: true
        hostname: traction-acapy-admin.apps.silver.devops.gov.bc.ca
        annotations:
          route.openshift.io/termination: edge

    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 250m
        memory: 250Mi

  tenant_proxy:
    image:
      pullPolicy: Always

    networkPolicy:
      enabled: true
      ingress:
        enabled: true
        namespaceSelector:
          network.openshift.io/policy-group: ingress

    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

  ui:
    image:
      pullPolicy: Always

    showOIDCReservationLogin: true
    
    oidc:
      active: true
      showInnkeeperAdminLogin: true
      showWritableComponents: false
      authority: https://loginproxy.gov.bc.ca/auth/realms/digitaltrust-citz
      jwksUri: https://loginproxy.gov.bc.ca/auth/realms/digitaltrust-citz/protocol/openid-connect/certs
      extraQueryParams: '{"kc_idp_hint":"idir"}'
      realm: "digitaltrust-citz"
      reservationForm: >-
        {
          "formDataSchema": {
            "type": "object",
            "properties": {
              "ministry": {
                "type": "string"
              },
              "contactName": {
                "type": "string"
              },
              "tenantReason": {
                "type": "string"
              }
            },
            "required": ["ministry", "contactName", "tenantReason"]
          },
          "formUISchema": {
            "type": "VerticalLayout",
            "elements": [
              {
                "type": "Control",
                "scope": "#/properties/ministry",
                "label": "Ministry"
              },
              {
                "type": "Control",
                "scope": "#/properties/contactName",
                "label": "Contact Name"
              },
              {
                "type": "Control",
                "scope": "#/properties/tenantReason",
                "label": "Purpose of Tenant",
                "options": {
                  "multi": true
                }
              }
            ]
          }
        }
    
    smtp:
      server: apps.smtp.gov.bc.ca
      port: 25
      senderAddress: DoNotReplyTractionPROD@gov.bc.ca
      innkeeperInbox: "lucas.o'neil@gov.bc.ca,emiliano.sune@quartech.com"
    
    networkPolicy:
      enabled: true
      ingress:
        enabled: true
        namespaceSelector:
          network.openshift.io/policy-group: ingress
    
    
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

    resources:
      limits:
        memory: 250Mi
      requests:
        cpu: 120m
        memory: 128Mi
  
  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: edge
