global:
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca

traction:
  acapy:
    image:
      pullPolicy: Always

    secrets:
      api:
        retainOnUninstall: true
        existingSecret: "traction-acapy-api"

    extraEnvVarsSecret: "traction-acapy-plugin-innkeeper"

    argfile.yml:
      preserve-exchange-records: false
      tails-server-base-url: https://tails-dev.vonx.io
      tails-server-upload-url: https://tails-dev.vonx.io

    ledgers.yml:
      - id: bcovrin-test
        is_production: true
        is_write: true
        genesis_url: "http://test.bcovrin.vonx.io/genesis"
        endorser_did: "DfQetNSm7gGEHuzfUvpfPn"
        endorser_alias: "bcovrin-test-endorser"
      - id: candy-dev
        is_production: true
        is_write: true
        genesis_url: "https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/dev/pool_transactions_genesis"
        endorser_did: "85DZerr49BLCuG5wWyDviy"
        endorser_alias: "candy-dev-endorser"
      - id: candy-test
        is_production: true
        is_write: false
        genesis_url: "https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/test/pool_transactions_genesis"
      - id: candy-prod
        is_production: true
        is_write: false
        genesis_url: "https://raw.githubusercontent.com/ICCS-ISAC/dtrust-reconu/main/CANdy/prod/pool_transactions_genesis"

    plugin-config.yml:
      traction_innkeeper:
        innkeeper_wallet:
          print_key: true
          print_token: true
          connect_to_endorser:
            - endorser_alias: bcovrin-test-endorser
              ledger_id: bcovrin-test
            - endorser_alias: candy-dev-endorser
              ledger_id: candy-dev
          create_public_did:
            - bcovrin-test
            - candy-dev
        reservation:
          expiry_minutes: 7200

    walletStorageConfig:
      url: traction-database-primary:5432

    walletStorageCredentials:
      admin_account: walletman
      existingSecret: traction-database-acapy
      secretKeys:
        adminPasswordKey: walletman-password
        userPasswordKey: acapy-password

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetMemoryUtilizationPercentage: 0
      targetCPUUtilizationPercentage: 80
      stabilizationWindowSeconds: 0

    networkPolicy:
      enabled: true
      ingress:
        enabled: true
        namespaceSelector:
          network.openshift.io/policy-group: ingress

    ingress:
      agent:
        enabled: true
        hostname: traction-acapy-dev.apps.silver.devops.gov.bc.ca
        annotations:
          route.openshift.io/termination: edge
      admin:
        enabled: true
        hostname: traction-acapy-admin-dev.apps.silver.devops.gov.bc.ca
        annotations:
          route.openshift.io/termination: edge

    resources:
      limits:
        memory: 500Mi
    postgresql:
      enabled: false

  tenant_proxy:
    image:
      pullPolicy: Always

    networkPolicy:
      enabled: true
      ingress:
        enabled: true
        namespaceSelector:
          network.openshift.io/policy-group: ingress
    
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

  ui:
    showOIDCReservationLogin: true
    quickConnectEndorserName: "bcovrin-test-endorser"

    image:
      pullPolicy: Always

    existingSecret: ""

    ux:
      infoBanner:
        message: "Traction DEV Environment"
        messageLevel: info
        showMessage: true

    oidc:
      active: true
      authority: https://dev.loginproxy.gov.bc.ca/auth/realms/digitaltrust-citz
      jwksUri: https://dev.loginproxy.gov.bc.ca/auth/realms/digitaltrust-citz/protocol/openid-connect/certs
      extraQueryParams: '{"kc_idp_hint":"idir"}'
      reservationForm: |-
        {
          "formDataSchema": {
            "type": "object",
            "properties": {
              "ministry": {
                "type": "string"
              },
              "contactName": {
                "type": "string"
              },
              "tenantReason": {
                "type": "string"
              }
            },
            "required": ["ministry", "contactName", "tenantReason"]
          },
          "formUISchema": {
            "type": "VerticalLayout",
            "elements": [
              {
                "type": "Control",
                "scope": "#/properties/ministry",
                "label": "Ministry"
              },
              {
                "type": "Control",
                "scope": "#/properties/contactName",
                "label": "Contact Name"
              },
              {
                "type": "Control",
                "scope": "#/properties/tenantReason",
                "label": "Purpose of Tenant",
                "options": {
                  "multi": true
                }
              }
            ]
          }
        }

    smtp:
      server: apps.smtp.gov.bc.ca
      port: 25
      senderAddress: DoNotReplyTractionDEV@gov.bc.ca
      innkeeperInbox: "lucas.o'neil@gov.bc.ca,emiliano.sune@quartech.com"

    networkPolicy:
      enabled: true
      ingress:
        enabled: true
        namespaceSelector:
          network.openshift.io/policy-group: ingress

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetMemoryUtilizationPercentage: 0
      targetCPUUtilizationPercentage: 80
      stabilizationWindowSeconds: 0

  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: edge
