apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bc0192-prod

resources:
- ../../bases/crunchy-cluster/
- ../../bases/monitoring/ 

patches:
  - patch: |-
      - op: replace
        path: /spec/instances/0/resources
        value:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 500Mi
      - op: replace
        path: /spec/patroni/dynamicConfiguration/postgresql/parameters
        value:
          max_connections: 500
          max_slot_wal_keep_size: 128MB
          max_wal_size: 1GB
          min_wal_size: 32MB
          shared_buffers: 500MB
          wal_buffers: "-1"
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: 10Gi
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/volume/volumeClaimSpec/resources/requests/storage
        value: 24Gi
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/schedules/full
        value: 0 0 * * *
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/schedules/incremental
        value: 0 * * * *
    target:
      kind: PostgresCluster
      name: traction-database
  - patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: monitoring-grafana-agent
    target:
      kind: Ingress
      name: monitoring-grafana-agent
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: bc0192-prod
    target:
      kind: RoleBinding
      name: monitoring-grafana-agent
