apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: e79518-prod

resources:
- ../../bases/monitoring/

patches:
  - patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: monitoring-grafana-agent
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: e79518-prod
    target:
      kind: RoleBinding
      name: monitoring-grafana-agent
