kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-grafana-agent
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana-agent
subjects:
  - kind: ServiceAccount
    name: monitoring-grafana-agent
    namespace: namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-grafana-agent
