def PIPELINE_NAME = "tails-server"

def LIB_NAME= "custom-lib"
def LIB_REPO = "https://github.com/bcgov/trust-over-ip-configurations.git"
def LIB_BRANCH = "main"
library identifier: "${LIB_NAME}@${LIB_BRANCH}",
        retriever: modernSCM(
          [$class: 'GitSCMSource',
          remote: "${LIB_REPO}",
          branches: [[name: "*/${LIB_BRANCH}"]]])

node {
  stage("Init") {
    script {
      dir(''){
        checkout scm
        config = load "jenkins/${PIPELINE_NAME}/config.groovy"
      }
    }
  }

  config.BUILDS.each {
    stage("Build ${it}") {
      script {
        openshift.withCluster() {
          openshift.withProject() {
            echo "Building the ${it} image ..."
            build(openshift, "${it}", config.WAIT_TIMEOUT)
          }
        }
      }
    }
  }

  stage("Deploy ${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}") {
    script {
      deploy("${config.IMAGE_NAME}",
             "${config.APP_NAME}",
             "${config.PREFIX}",
             "${config.SUFFIX}",
             "${config.NAME_SPACE}",
             "${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}")
    }
  }
}